version: 0.0
os: linux
files:
  - source: /
    destination: /quoterepo
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300