version: 0.0
os: linux
files:
  - source: /
    destination: /home/quoterepo
# permissions:
#   - object: /home/ubuntu
#     owner: ubuntu
#     group: ubuntu
#     type:
#       - directory
#       - file
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300