# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Initialize Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
    
      # Install dependencies -- build -- test
      - name: Install dependencies build and test
        run: |
          npm install
          npm run build --if present
          
      # Run unit test
      - name: Unit test
        id: unit-test
        run: |
          EXPECTED_RESULT=$(cat << EOF
          PASS T01
          PASS T02
          PASS T03
          EOF
          )
          EXPECTED_RESULT="${EXPECTED_RESULT//'%'/'%25'}"
          EXPECTED_RESULT="${EXPECTED_RESULT//$'\n'/'%0A'}"
          EXPECTED_RESULT="${EXPECTED_RESULT//$'\r'/'%0D'}"
          echo "::set-output name=OUTPUT::$EXPECTED_RESULT"
          cd serverSide
          node testAllQuotes.js
      
      # Check if tests passed
      - name: Pass check
        if: steps.unit-test.outputs.OUTPUT == "$EXPECTED_RESULT"
        run: echo "test passed"

